FROM node:20.9-alpine AS base
WORKDIR /app
RUN apk add --no-cache libc6-compat

COPY package*.json ./
RUN npm ci
COPY . .
RUN npx prisma generate

ENV NODE_ENV=production
CMD ["node", "-r", "ts-node/register", "lib/workers/index.ts"]
