export const RETRIEVAL_POLICY = {
  DEFAULT_TOP_K: 5,
  MAX_TOP_K: 25,
  MAX_PAGE: 100,
  MIN_QUERY_LENGTH: 2,
  DEFAULT_MIN_SCORE: 0,
  RECENCY_DAYS: 180,
  PREFETCH_MULTIPLIER: 3,
  DEFAULT_IVFFLAT_PROBES: 10,
  MAX_IVFFLAT_PROBES: 40,
  VECTOR_WEIGHT: 0.65,
  KEYWORD_WEIGHT: 0.35,
} as const

export type RetrievalPolicy = typeof RETRIEVAL_POLICY
